### PR TITLE
Finalize 0.4.0

### PR DESCRIPTION
**Pull request by orbeckst**
- test 2.7, 3.5 (for the last time); add tests for 3.8 and 3.9
- update CHANGEs (deprecate 2.7 and 3.5)
- update docs
- contribute to #113

### CODE REVIEW

**Comment by orbeckst** [comment]
@davidlmobley @dotsdl please have a look; I'd be happy to release this as 0.4.0.

(alchemtest 0.4.0 is already out)

**Comment by dotsdl** [comment]
Taking a look now; thank you @orbeckst!

**Review by dotsdl — APPROVED** [review]
This looks ready to go @orbeckst! Thank you so much for putting this release together, as well as your continued leadership and attention to detail in the PRs that have gone into it.

Thank you @wehs7661 and @xiki-tempula for your contributions over the past year; we look forward to getting these distributed as 0.4.0!

**Comment by davidlmobley** [comment]
I won't get to review on this anytime soon, so feel free to go ahead without me.

**Pull request merged**
