### PR TITLE
amber TI parser (#10)

### PR DESCRIPTION
**Pull request by orbeckst**
This PR supercedes PR #32: rebased and cleaned up history.

NOTE: This PR must be *merged* (not rebased, otherwise author information is lost)

### CODE REVIEW

**Comment by orbeckst** [comment]
I will look at this later in the afternoon. Hopefully the tests will still pass.

**Comment by orbeckst** [comment]
@shuail please review when you have time.

**Comment by shuail** [comment]
@orbeckst thanks a lot! I have to run into a flight, will review this later today.

**Comment by dotsdl** [comment]
I pulled the amber tests for TI into the existing test module for less code duplication. The effect is identical as before. Thanks for all your work on this, @shuail and @orbeckst!

**Comment by davidlmobley** [comment]
Just spectating here. Nice job everyone -- great to see the process working. :)

**Comment by orbeckst** [comment]
I am trying out `pragma: no cover` to get the 95% target. The justification is to [be explicit about what you exclude from test coverage](https://www.mxsasha.eu/blog/2014/09/11/why-and-how-test-coverage-100/). I haven't done this that aggressively before but it seems a good idea, and with @dotsdl 's great initial coverage we can be very clear about which code paths are tested and which ones are not.

(Of course, the tests themselves still have to make sense but once you read the source and see that 
```python
                # FIXME: assumes fields are only integers or floats
                if '*' in value:            # Fortran format overflow
                    result.append(float('Inf') )
```
is not covered (and not excluded from coverage) then you get an idea where potential pain points are.)

**Comment by orbeckst** [comment]
I cleaned up the history and force-pushed, sorry for any inconvenience.

When you `git pull` you should see a forced update. If not, make sure that you have no changes, then `git reset --hard master; git pull`.

**Comment by orbeckst** [comment]
@dotsdl feel free to review but please don't merge until @shuail got a chance to review. I want to make sure that his code goes in properly.

@shuail if you and @dotsdl both approve you can *merge* the PR as is. (Do not rebase or squash because (1) this commit history has meaningful smaller commits and (2) rebasing is going to mess up the author attributions on any commit that has already gone through a rebase.) Thanks!

Excellent work!

**Comment by orbeckst** [comment]
Feel free to merge ("Merge pull request"). You can then delete this branch.

**Pull request merged**
