### PR TITLE
gmx parsers now drop duplicate columns

### PR DESCRIPTION
**Pull request by dotsdl**
Some of our datasets, such as [`alchemtest.gmx.benzene`](https://github.com/alchemistry/alchemtest/tree/master/src/alchemtest/gmx/benzene), feature duplicate columns in their data files. Previously this was handled after initial parsing with `pandas.read_csv`, but as of the latest `pandas` release this function disallows duplicate column names on entry.

We now mark duplicate column names before entry into `pandas.read_csv`, and we filter these duplicate columns from the resulting dataframe after this initial parsing.

### CODE REVIEW

**Comment by orbeckst** [comment]
I had to play around a bit to understand what the duplicated columns in our data look like and **if it is ok to just drop them** – I think @dotsdl and maybe @lee212 had thought more about this but I don't remember any discussions.

I am not sure why Gromacs produces these duplicated columns (maybe @mrshirts knows?).

In any case, I empirically looked at two Gromacs datasets and at least in these cases it looks as if **the data in columns with duplicated names are (almost) identical**. Therefore, dropping duplicated columns does not lead to errors.


# Dataset analysis
Everything else below are notes on how I looked at the data. Note that I used Pandas version '0.24.2', which does _not_ raise an error for duplicated columns but instead issues a warning.

```python
from alchemtest.gmx import load_benzene, load_expanded_ensemble_case_1
import alchemlyb
from alchemlyb.parsing import gmx
import pandas as pd
import numpy as np

print(alchemlyb.__version__)     # '0.2.0-rc2+68.g710a522'
print(pd.__version__)            # '0.24.2'
```


## benzene dataset

```python
fn = dataset['data']['VDW'][1]
headers = gmx._get_headers(fn)
names = [gmx._get_value_by_key(headers, 's{}'.format(x), 'legend') for x in range(len(headers)) if 's{}'.format(x) in headers]
print(names)
```
gives
```
['dH/d\\xl\\f{} fep-lambda = 0.0500',
 '\\xD\\f{}H \\xl\\f{} to 0.0000',
 '\\xD\\f{}H \\xl\\f{} to 0.0500',
 '\\xD\\f{}H \\xl\\f{} to 0.1000',
 '\\xD\\f{}H \\xl\\f{} to 0.2000',
 '\\xD\\f{}H \\xl\\f{} to 0.3000',
 '\\xD\\f{}H \\xl\\f{} to 0.4000',
 '\\xD\\f{}H \\xl\\f{} to 0.5000',
 '\\xD\\f{}H \\xl\\f{} to 0.6000',
 '\\xD\\f{}H \\xl\\f{} to 0.6500',
 '\\xD\\f{}H \\xl\\f{} to 0.7000',
 '\\xD\\f{}H \\xl\\f{} to 0.7500',
 '\\xD\\f{}H \\xl\\f{} to 0.7500',
 '\\xD\\f{}H \\xl\\f{} to 0.8000',
 '\\xD\\f{}H \\xl\\f{} to 0.8500',
 '\\xD\\f{}H \\xl\\f{} to 0.9000',
 '\\xD\\f{}H \\xl\\f{} to 0.9500',
 '\\xD\\f{}H \\xl\\f{} to 1.0000',
 'pV (kJ/mol)']
```
i.e., the column **'\\xD\\f{}H \\xl\\f{} to 0.7500'** is duplicated.  Following the code in https://github.com/alchemistry/alchemlyb/blob/710a522cc38b80482d57f964d2ee5f334b01fe3d/src/alchemlyb/parsing/gmx.py#L240 I can look into the original data (needs older pandas  – this one just warns _UserWarning: Duplicate names specified. This will raise an error in the future._)

```python
header_cnt = len(headers['_raw_lines'])
xaxis = gmx._get_value_by_key(headers, 'xaxis', 'label')
cols = [xaxis] + names
df = pd.read_csv(fn, sep=r"\s+", header=None, skiprows=header_cnt, na_filter=True, memory_map=True, names=cols, dtype=np.float64, float_precision='high')

print(df.columns[12:14])
```
gives `Index(['\xD\f{}H \xl\f{} to 0.7500', '\xD\f{}H \xl\f{} to 0.7500.1'], dtype='object')`. The difference between these two columns
```python
delta = df[r'\xD\f{}H \xl\f{} to 0.7500'] - df[r'\xD\f{}H \xl\f{} to 0.7500.1']
print(delta.min(), delta.max())
```
gives **-4.0000000041118255e-06    4.0000000041118255e-06**, so the two columns are rather similar but not identical, certainly not to float64 machine precision.

## expanded ensemble case_1
```python
d = load_expanded_ensemble_case_1()
fn = d['data']['AllStates'][0]
gmx._extract_state(fn)
```
gives
```
(None,
 ['fep-lambda', 'coul-lambda', 'vdw-lambda', 'restraint-lambda'],
 [[0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0],
  [0.0, 0.05, 0.0, 0.0],
  [0.0, 0.1, 0.0, 0.0],
  [0.0, 0.16, 0.0, 0.0],
  [0.0, 0.22, 0.0, 0.0],
  [0.0, 0.28, 0.0, 0.0],
  [0.0, 0.34, 0.0, 0.0],
  [0.0, 0.4, 0.0, 0.0],
  [0.0, 0.46, 0.0, 0.0],
  [0.0, 0.52, 0.0, 0.0],
  [0.0, 0.6, 0.0, 0.0],
  [0.0, 0.68, 0.0, 0.0],
  [0.0, 0.76, 0.0, 0.0],
  [0.0, 0.84, 0.0, 0.0],
  [0.0, 0.92, 0.0, 0.0],
  [0.0, 1.0, 0.0, 0.0001],
  [0.0, 1.0, 0.1, 0.0002],
  [0.0, 1.0, 0.2, 0.0004],
  [0.0, 1.0, 0.3, 0.001],
  [0.0, 1.0, 0.4, 0.002],
  [0.0, 1.0, 0.48, 0.004],
  [0.0, 1.0, 0.52, 0.01],
  [0.0, 1.0, 0.6, 0.02],
  [0.0, 1.0, 0.68, 0.04],
  [0.0, 1.0, 0.76, 0.1],
  [0.0, 1.0, 0.84, 0.2],
  [0.0, 1.0, 0.92, 0.4],
  [0.0, 1.0, 1.0, 1.0]])
```

And getting column names
```python
headers = gmx._get_headers(fn)
names = [gmx._get_value_by_key(headers, 's{}'.format(x), 'legend') for x in range(len(headers)) if 's{}'.format(x) in headers]
print(names)
```
gives
```
['Thermodynamic state', 'Total Energy (kJ/mol)', 'dH/d\\xl\\f{} fep-lambda = 0.0000', 'dH/d\\xl\\f{} coul-lambda = 1.0000', 'dH/d\\xl\\f{} vdw-lambda = 0.1000', 'dH/d\\xl\\f{} restraint-lambda = 0.0002', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.0000, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.0000, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.0000, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.0000, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.0000, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.0500, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.1000, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.1600, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.2200, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.2800, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.3400, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.4000, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.4600, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.5200, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.6000, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.6800, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.7600, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.8400, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 0.9200, 0.0000, 0.0000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.0000, 0.0001)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.1000, 0.0002)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.2000, 0.0004)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.3000, 0.0010)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.4000, 0.0020)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.4800, 0.0040)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.5200, 0.0100)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.6000, 0.0200)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.6800, 0.0400)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.7600, 0.1000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.8400, 0.2000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 0.9200, 0.4000)', '\\xD\\f{}H \\xl\\f{} to (0.0000, 1.0000, 1.0000, 1.0000)']
```
where **'\\xD\\f{}H \\xl\\f{} to (0.0000, 0.0000, 0.0000, 0.0000)'** is repeated 4 times.

Read data
```python
header_cnt = len(headers['_raw_lines'])
xaxis = gmx._get_value_by_key(headers, 'xaxis', 'label')
cols = [xaxis] + names
df = pd.read_csv(fn, sep=r"\s+", header=None, skiprows=header_cnt, na_filter=True, memory_map=True, names=cols, dtype=np.float64, float_precision='high')
```

and look at the columns
```python
df.columns[7:12]
```
```
Index(['\xD\f{}H \xl\f{} to (0.0000, 0.0000, 0.0000, 0.0000)',
       '\xD\f{}H \xl\f{} to (0.0000, 0.0000, 0.0000, 0.0000).1',
       '\xD\f{}H \xl\f{} to (0.0000, 0.0000, 0.0000, 0.0000).2',
       '\xD\f{}H \xl\f{} to (0.0000, 0.0000, 0.0000, 0.0000).3',
       '\xD\f{}H \xl\f{} to (0.0000, 0.0000, 0.0000, 0.0000).4'],
      dtype='object')
```
Subtracting them from each other:
```
n [44]: delta = {}
    ...: for i in range(7, 12):
    ...:     delta[i] = {}
    ...:     for j in range(i+1, 12):
    ...:         d = df.iloc[:, i] - df.iloc[:, j]
    ...:         delta[i][j] = d
    ...:         print("{} - {}: min = {}, max = {}".format(i, j, d.min(), d.max()))
    ...:
7 - 8: min = 0.0, max = 0.0
7 - 9: min = 0.0, max = 0.0
7 - 10: min = 0.0, max = 0.0
7 - 11: min = 0.0, max = 0.0
8 - 9: min = 0.0, max = 0.0
8 - 10: min = 0.0, max = 0.0
8 - 11: min = 0.0, max = 0.0
9 - 10: min = 0.0, max = 0.0
9 - 11: min = 0.0, max = 0.0
10 - 11: min = 0.0, max = 0.0
```
shows that they all contain identical values.

# Conclusions

In the two cases that I looked at it looks as if **the data in columns with duplicated names are (almost) identical**. Therefore, dropping duplicated columns in alchemlyb does not lead to errors.

**Comment by orbeckst** [comment]
Many thanks for the quick fix, @dotsdl !

**Comment by dotsdl** [comment]
Thanks for the more thorough analysis @orbeckst! I should have shared more details of what I had found, but since we [drop duplicate columns anyway later on](https://github.com/alchemistry/alchemlyb/blob/master/src/alchemlyb/parsing/gmx.py#L44) this didn't change what we were seeing downstream. I am glad you checked, though, because we know we've been systematically wrong before (e.g. NAMD parsing). This attention to detail is a defining feature of this project.

**Comment by orbeckst** [comment]
The lines https://github.com/alchemistry/alchemlyb/blob/abd513f2d9f2be425b1cdbcc6cd78a073de37808/src/alchemlyb/parsing/gmx.py#L44-L45 could go now, couldn't they?

**Comment by dotsdl** [comment]
Indeed, they *should* be able to. Do you prefer I remove them? I'd be happy to.

**Comment by orbeckst** [comment]
Yes, please.

**Pull request merged**
