### PR TITLE
prepare release 2.4.0

### LINKED ISSUE #385: swithc from setup.py to pyproject.toml
We should eventually modernize our package building configuration and procedure and remove setup.py/setup.cfg and switch to pyproject.toml.

Not urgent but should be done.

### PR DESCRIPTION
**Pull request by orbeckst**
- towards #396 
- fix #385 (modernize build system)
- finalize CHANGES

### CODE REVIEW

**Comment by orbeckst** [comment]
Note: needs to be *merged* (not squashed) because the blackify-commit should be on its own so that .git-ignore-revs correctly works.

**Review by xiki-tempula — APPROVED** [review]

**Comment by xiki-tempula** [comment]
Later on if I have time, I think `ruff` is the thing that people use now.

**Comment by xiki-tempula** [comment]
Might be good to squash merge next time.

**Comment by orbeckst** [comment]
Thanks for the review.

> Might be good to squash merge next time.

This needed to be merged so that commit IDs remained intact for the black-only commit or how would you have done the .git-ignore-revs?

**Comment by xiki-tempula** [comment]
I see. Sorry I don't quite know how `git-ignore-revs` works.

**Comment by orbeckst** [comment]
https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html

**Pull request merged**
