### PR TITLE
Removed extraction of dHdl avg and components in AMBER parser

### PR DESCRIPTION
**Pull request by DrDomenicoMarson**
Addressing issue #226, I removed the useless extraction of dHdl averages (and dHdl components at the same time).

PS: I also made a really small adjustment to the ```skip_lines``` method of ```SectionParser```, as it stated it skipped a given number of "files" (????) while it should obviously be "lines" :-)

### CODE REVIEW

**Comment by DrDomenicoMarson** [comment]
I see the code coverage went down a little bit, I don't think it is really a problem, but I don't understand why it decreased, as the new code should be executed during the tests, as it was before... 

Loosely related, I noticed there are some ```pragma: no cover``` comments, should I address them also in separate issues with new tests, right?

**Comment by xiki-tempula** [comment]
> I see the code coverage went down a little bit, I don't think it is really a problem, but I don't understand why it decreased, as the new code should be executed during the tests, as it was before...

No worry. As long as the patch is good, it is fine. The project goes down as the number of the uncovered line remain unchanged while the total amount of lines has decreased.

> Loosely related, I noticed there are some pragma: no cover comments, should I address them also in separate issues with new tests, right?

Ideally yes, but adding new tests without changing the code base is usually fine.

**Review by xiki-tempula — APPROVED** [review]
LGTM. @orbeckst Shall I just merge this?

**Comment by orbeckst** [comment]
Please squash-merge if you’re happy with it. Just synthesize all commit messages into something readable.

**Pull request merged**
