### PR TITLE
fixed AMBER parser logging

### PR DESCRIPTION
**Pull request by orbeckst**
- log to module logger and not the root logger
- removed redundant ERROR and WARNING text
- removed redundant trailing newlines

### CODE REVIEW

**Review by xiki-tempula — APPROVED** [review]
LGTM. 
A bit confused when I see that
`logger = logging.getLogger("alchemlyb.parsers.Amber")`
was added before this commit.

**Comment by xiki-tempula** [comment]
@orbeckst Shall I just squash and merge this commit or do you prefer to do the squash and merge it?

**Comment by orbeckst** [comment]
What do you mean, what's confusing?

The loggers had been in the original code but they did not use the specific logger but the root logger.

If you think anything needs changing, just ask for revisions ;-).

**Comment by orbeckst** [comment]
You squash-merge when you're satisfied. I just assigned you.

**Comment by xiki-tempula** [comment]
I mean when I saw that logger is used instead of logging, I would assume that one would need to create a logger, but the creation of the logger is not in this PR so I was initially quite confused. Then I noticed that the logger was created but never used.

**Pull request merged**
