### PR TITLE
Somewhat-new AMBER parser

### PR DESCRIPTION
**Pull request by DrDomenicoMarson**
Hi, I addressed what I stated in #219 and #222, skipping point 3).
To make the test pass, the PR66 of alchemtest has to be accepted, once it's accepted all tests should pass!

### CODE REVIEW

**Comment by orbeckst** [comment]
Please reopen PR #219 and _after_ that is merged, you can address anything else. You can then rebase against the main branch. We do not want to review too many things together.

**Comment by DrDomenicoMarson** [comment]
I'm so sorry, I closed this because the new PR addresses everything in one go, and I had no more access to the previous code, as I moved on on the same file/fork!
The new code passed all the tests (once the alchemtest is updated), and I also tested it with my own data comparing with what I obtained with the original implementation, and the results match perfectly... is it really impossible to review it like that? 
I don't know if I can go back and re-do everything step by step, I'm  also low on time 😢 
I made everything during my holidays, but now I have to go back to other stuff and I don't know how much time I can spend on this in the next days!

**Comment by DrDomenicoMarson** [comment]
If it's not possible I'll try to backup the previous PR and continue using my fork for my work for the time being if you prefer!

**Comment by orbeckst** [comment]
Yes, please reset the PR to the stage where it only addresses the original problem.

Thanks!

**Comment by DrDomenicoMarson** [comment]
Is it possible to do so in GitHub? It was in a branch I deleted, now in master I only have what's now in this PR.. maybe I can just re-fork it and re-implement just the change, but I have to do that with a new PR I think!

PS: I can't make the new PR anyway if nobody accept the alchemtest PR, because the tests won't pass.

**Comment by orbeckst** [comment]
See comments https://github.com/alchemistry/alchemlyb/pull/219#issuecomment-1244213358 — the plan is to **close this PR**.

**Pull request closed without merging**
