### PR TITLE
Enable continuous integration with TravisCI

### PR DESCRIPTION
**Pull request by ianmkenney**
[Alchemlyb TravisCI Panel](https://travis-ci.org/alchemistry/alchemlyb)

Python Versions:
* 2.7

Branches:
* master
* develop (not a major branch yet)

### CODE REVIEW

**Comment by ianmkenney** [comment]
@dotsdl It looks like pymbar doesn't support python 3 syntax
```
Collecting pymbar (from alchemlyb==0.1.0.dev0)

  Downloading pymbar-2.1.0-beta.tar.gz (50kB)

    100% |████████████████████████████████| 51kB 6.4MB/s 

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-build-2j9i1paj/pymbar/setup.py", line 136, in <module>

        main()

      File "/tmp/pip-build-2j9i1paj/pymbar/setup.py", line 132, in main

        setupKeywords = buildKeywordDictionary()

      File "/tmp/pip-build-2j9i1paj/pymbar/setup.py", line 121, in buildKeywordDictionary

        for key in sorted( setupKeywords.iterkeys() ):

    AttributeError: 'dict' object has no attribute 'iterkeys'
```

I assume this means that we can only test python 2

**Comment by ianmkenney** [comment]
@dotsdl Please review.

**Comment by davidlmobley** [comment]
As far as I know, `pymbar` should support Python 3; at least, @jchodera is trying to make everything python3 compatible these days. Perhaps he can advise.

**Comment by davidlmobley** [comment]
Also, I think @mrshirts should probably be able to comment since he's one of the `pymbar` devs as well. I think at this point it's critical we move to python3 as python2 support is going away starting this year in many major packages, IIRC.

**Comment by davidlmobley** [comment]
It's in the [https://github.com/choderalab/pymbar/blob/master/.travis.yml](`.travis.yml`) for pymbar, so it looks like they're trying to support it at least. I suggest an issue on the issue tracker.

**Comment by mrshirts** [comment]
I believe it's just the setup that doesn't support python 3.  I think John and Levi are working on this now?

**Comment by jchodera** [comment]
What is the precise problem? Can you paste an example of what you are trying to do that doesn't work?

**Comment by jchodera** [comment]
I know of no python 3 issues with pymbar.

**Comment by jchodera** [comment]
Ah, I just saw https://github.com/alchemistry/alchemlyb/pull/5#issuecomment-269848687.

That's `pymbar-2.1.0-beta`, which is not python 3.x compatible. You'll have to use the `pymbar 3` release, which was currently only available via github or `conda` installs.

I've pushed the `pymbar-3.0.0.dev0` package to pypi, since I think that's what you're using:
https://pypi.python.org/pypi/pymbar/3.0.0.dev0

We're in the process of cleaning up the documentation and have a full 3.0.0 release scheduled for Friday, where we'll also update the license to MIT.

**Comment by ianmkenney** [comment]
I will add python 3.5 to testing since we expect it to work in the near future. Thanks!

**Comment by jchodera** [comment]
Looks like `six` is imported in `setup.py` but wasn't added to `requirements`. I've created a PR to fix: https://github.com/choderalab/pymbar/pull/251

**Comment by jchodera** [comment]
We're still hoping to update the release on Friday, so I would suggest you simply `pip install six` before you install `pymbar` at this point to work around this issue in the meantime.

**Comment by ianmkenney** [comment]
See latest build for 2.7 for compilation error.

**Comment by jchodera** [comment]
That's very odd. Trying to replicate locally.

**Comment by ianmkenney** [comment]
I can try it in 6-7 hours once I'm back from my family New Years event

**Comment by jchodera** [comment]
I've disabled the C extensions and pushed a new `3.0dev3` package to pypi. You may need to use the `--pre` flag for `pip` to pick this version up.

**Comment by ianmkenney** [comment]
@jchodera reran the build and it worked. Thanks for the assistance!

**Comment by jchodera** [comment]
Great! Sorry for the hassle here---you uncovered a lot of issues that we hadn't realized existed.

**Comment by dotsdl** [comment]
Awesome, thanks all for this! Merging.

**Pull request merged**
