### PR TITLE
Correct TI error estimation

### PR DESCRIPTION
**Pull request by harlor**
The error estimation for the free energy differences doesn't consider covariances. So I suggest to also take them into account.

### CODE REVIEW

**Comment by harlor** [comment]
> Sampling at independent lambdas should be uncorrelated, since they are expected to come from independent simulations. Nonzero covariance is likely to be noise.

I completely agree. I was a bit imprecise. Acually I don't mean covariances between the mean dhdls but of the trapezoid areas. When one mean dhdl changes it changes the area of 2 trapezoids (Except it is a boundary value). 

Example with 3 dhdl-mean-values - 3 lambdas - 2 delta_lamdas:

Integral calculates as:
I = deltal_1*(y1+y2)/2 + deltal_2*(y2+y3)/2

Using propagation of uncertainty the integral has the variance:
dI^2 = (dy1*deltal_1/2)^2 + (dy2*(deltal_1+deltal_2)/2)^2 + (dy3*deltal_3/2)^2

**Comment by mrshirts** [comment]
But we can rewrite the contribution of the trapezoids into a sum of independent calculations  I.e. although it's _derived_ as the area of a set of trapezoids, it is writeable (give it a try!) as:

\sum w_i <dh/dl>_i  

where w_i is a weight determined by the choice of lambdas and <dh/dl>_i  is the ensemble average of dh/dl at state i. No correlations are necessary; at best, they should cancel out.

Note that I realized that I actually haven't looked at THIS code in alchemlyb.  The error analysis code I wrote is at: https://github.com/MobleyLab/alchemical-analysis.  If the error analysis calculation in alchemlyb does not reflect the code in alchemical-analysis, then the alchemlyb should be checked and updated.   

But it is possible (and far preferable) to do WITHOUT any correlation matrix. Any autocorrelation matrix approach assume simple error propagation, which may not quite hold, and thus even if the overall effect is correct in the limit that simple error propagation is correct, they will introduce some error for most calculations.

**Comment by harlor** [comment]
> Note that I realized that I actually haven't looked at THIS code in alchemlyb. The error analysis code I wrote is at: https://github.com/MobleyLab/alchemical-analysis. If the error analysis calculation in alchemlyb does not reflect the code in alchemical-analysis, then the alchemlyb should be checked and updated.

If I'm not mistaken, the error estimates differ. With this pull request I actually try to reproduce the results from alchemical-analysis.

**Comment by harlor** [comment]
Sorry these commits should have never appeared here. This PR can be closed.

**Pull request closed without merging**
