### PR TITLE
Issue futurewarning

### LINKED ISSUE #408: Pandas FutureWarning Cluttering output
Pandas FutureWarnings are cluttering output:
```
[alchemlyb/src/alchemlyb/estimators/bar_.py:100](alchemlyb/src/alchemlyb/estimators/bar_.py:100): FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  (len(groups.get_group(i)) if i in groups.groups else 0)
[alchemlyb/src/alchemlyb/estimators/bar_.py:122](alchemlyb/src/alchemlyb/estimators/bar_.py:122): FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  uk = groups.get_group(self._states_[k])
[alchemlyb/src/alchemlyb/estimators/bar_.py:127](alchemlyb/src/alchemlyb/estimators/bar_.py:127): FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  uk1 = groups.get_group(self._states_[k + 1])
```

### PR DESCRIPTION
**Pull request by jaclark5**
Fixes #408, by adapting code to resolve pandas FutureWarnings:
```
 [alchemlyb/src/alchemlyb/estimators/bar_.py:100](alchemlyb/src/alchemlyb/estimators/bar_.py:100): FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  (len(groups.get_group(i)) if i in groups.groups else 0)
[alchemlyb/src/alchemlyb/estimators/bar_.py:122](alchemlyb/src/alchemlyb/estimators/bar_.py:122): FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  uk = groups.get_group(self._states_[k])
[alchemlyb/src/alchemlyb/estimators/bar_.py:127](alchemlyb/src/alchemlyb/estimators/bar_.py:127): FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  uk1 = groups.get_group(self._states_[k + 1])
```

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
thanks for the fix.

(looks a bit uglier than it used to but if this what pandas wants...)

**Comment by orbeckst** [comment]
Let's include this fix in the 2.4.1 release #403

**Comment by jaclark5** [comment]
> thanks for the fix.
> 
> (looks a bit uglier than it used to but if this what pandas wants...)

@orbeckst The alternative is to have all lambda states be represented as tuples. so instead of:
`u_nk.columns.tolist() = [0, 0.25, 0.5, 0.75, 1.0]`
it will have to be:
`u_nk.columns.tolist() = [(0,), (0.25,), (0.5,), (0.75,), (1.0,)]`

**Comment by orbeckst** [comment]
Thanks @jaclark5 !

**Pull request merged**
